version: "3"
services:
  mongodb:
    image: mongo:4.2
    restart: always
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  app:
    image: spring-boot-docker.jar
    ports:
      - 8500:8500
    links:
      - mongodb
    expose:
      - 8500
    command: mvn clean spring-boot:run